config/routes.rb
PreviewifyDemo::Application.routes.draw do

  root :controller => :homepage, :action => :show

  resources :articles do
    member do
      post 'publish'
      post 'take_down'
    end
    resources :versions, :only => [:show] do
      member do
        post 'revert'
      end
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base

  previewify

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  # Previewify::Control allows you to switch between preview and live mode
  include Previewify::Control

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :show_preview

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.create(params[:article])
    redirect_to(edit_article_path(@article))
  end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(params[:article])
      redirect_to(@article, :notice => 'Article successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to(articles_url)
  end

  def publish
    @article = Article.find(params[:id])
    @article.publish!
    flash[:notice] = 'Article successfully published.'
    redirect_to :action => :index
  end

  def take_down
    @article = Article.find(params[:id])
    @article.take_down!
    flash[:notice] =  'Article successfully taken down.'
    redirect_to :action => :index
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  before_filter :preview_or_published

  def preview_or_published
    #This could be a function of current user, hostname, a parameter etc.
    show_preview(params.has_key?(:preview))
  end


  def show
    @articles = Article.most_recent
  end

end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController

  before_filter :show_preview

  def show
    @draft_article = Article.find(params[:article_id])
    @article = @draft_article.version(params[:id])
  end

  def revert
    @draft_article = Article.find(params[:article_id])
    @draft_article.revert_to_version_number!(params[:id])
    redirect_to article_url(@draft_article)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article_form.html.haml
= form_for(@article) do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body_text
  = f.text_area :body_text, :rows => 20, :cols => 40
  = f.submit 'Save'

app/views/articles/edit.html.haml
.articles_nav
  = link_to "Home", root_path
  = link_to "Articles", articles_path

%h1 Edit Article
= render 'article_form'

app/views/articles/index.html.haml
.articles_nav
  = link_to "Home", root_path
  = link_to "New", new_article_path

%h1 My Articles
%ul.articles
  - for article in @articles
    %li.article
      .title
        = link_to article.title, edit_article_path(article)
      - if article.published?
        .published
          .version_number
            Version
            = "#{article.version_number},"
          .last_updated
            last updated at
            = article.updated_at.to_formatted_s(:db)
          .status
            = " with unpublished changes" if article.has_unpublished_changes?
          .take_down
            = link_to "take down", article_path(article)+'?take_down=true'
      - else
        .unpublished
          .version_number
            Not published,
          .last_updated
            last updated at
            = article.updated_at.to_formatted_s(:db)
          .delete
            = button_to "Delete", article_path(article), :method => :delete, :confirm => "Are your sure?", :title => 'Permanently delete article'
      %ul
        - article.versions.each do |article_version|
          %li
            .published_version_number
              = link_to "Version #{article_version.version_number}", article_version_path(article_version, article_version.version_number)
            .published_on
              published on
              = article_version.published_on.to_formatted_s(:db)

app/views/articles/new.html.haml
.articles_nav
  = link_to "Home", root_path
  = link_to "Articles", articles_path

%h1 Write new Article
= render 'article_form'

app/views/articles/show.html.haml
.articles_nav
  = link_to "Home", root_path
  = link_to "Articles", articles_path

.review_header
  - if @article.published? && !@article.has_unpublished_changes?
    This is how your article currently appears
  - else
    -if params[:take_down]
      This is how your article would appear if you published it
    - else
      This is how your article will appear

.review
  = render '/article', :article => @article

= link_to "keep editing this article", edit_article_path(@article)

- if (!@article.published? || @article.has_unpublished_changes?) && !params[:take_down]
  = form_for :article, @article, :url => publish_article_path(@article), :html => {:method => :post} do |f|
    - if !@article.published?
      = f.submit 'Publish'
    - else
      = f.submit 'Publish changes'

- if @article.published? && params[:take_down]
  = form_for :article, @article, :url => take_down_article_path(@article), :html => {:method => :post} do |f|
    = f.submit 'Take down'

app/views/homepage/show.html.haml
.menu
  = link_to "Edit Articles", articles_path
%h1 Articles
- for article in @articles
  = render '/article', :article => article

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PreviewifyDemo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/versions/show.html.haml
Version
= @article.version_number
of this article was published on
= @article.published_on.to_formatted_s(:rfc822)
- if @draft_article.version_number == @article.version_number
  and this is how the article currently appears on your website:
- else
  and appeared as follows:
= render '/article', :article => @article

.footer
  - if @article.version_number != @draft_article.version_number || @draft_article.has_unpublished_changes?
    = form_for :article, @article, :url => revert_article_version_path(@article, @article.version_number), :html => {:method => :post} do |f|
      = f.submit 'Revert your draft to this version'